/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import java.beans.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class signupform extends javax.swing.JFrame {

    String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String Url = "jdbc:sqlserver://DESKTOP-TAQ595G\\SQLEXPRESS2:1433;database=BTL_OOP2;";
    String username = "sa";
    String password = "1234";
    Statement st;

    public signupform() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtname = new javax.swing.JTextField();
        btnSignup = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtConfirmPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtAddress = new javax.swing.JTextField();
        txtuserName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 758, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 750, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel2.setText("Name (*)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 143, 32));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setText("Address (*)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 296, 143, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel4.setText("Phone number (*)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 349, -1, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 487, 758, 11));
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 67, 442, 32));

        btnSignup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSignup.setText("Sign Up");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 505, 140, 36));

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 505, 136, 36));

        txtConfirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 235, 442, 36));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel5.setText("Username  (*)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 143, 35));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel6.setText("Password (*)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 183, 143, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel7.setText("Confirm password (*)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 241, -1, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel8.setText("Email");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 413, 117, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 408, 442, 38));
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 349, 442, 35));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 180, 442, 34));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 295, 442, 36));
        getContentPane().add(txtuserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 121, 442, 37));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Downloads\\abcc.jpg")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtConfirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPassActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed

        try {
            StringBuilder sb = new StringBuilder();
            if (txtname.getText().equals("")) {
                sb.append("Username is empty!\n");
                txtname.setBackground(Color.yellow);
                txtname.requestFocus();
            } else {
                txtname.setBackground(Color.white);
            }
            if (txtuserName.getText().equals("")) {
                sb.append("Username is empty!\n");
                txtuserName.setBackground(Color.yellow);
                txtuserName.requestFocus();
            } else {
                txtuserName.setBackground(Color.white);
            }

            if (new String(txtPassword.getPassword()).equals("")) {
                sb.append("Password is empty!\n");
                txtPassword.setBackground(Color.yellow);
                txtPassword.requestFocus();
            } else {
                txtPassword.setBackground(Color.white);
            }

            if (!new String(txtConfirmPass.getPassword()).equals(new String(txtPassword.getPassword()))) {
                sb.append("Password and confirm must be the same\n");
                txtConfirmPass.setBackground(Color.yellow);
            } else {
                txtConfirmPass.setBackground(Color.white);
            }
            if (txtAddress.getText().equals("")) {
                sb.append("Address is empty!\n");
                txtAddress.setBackground(Color.yellow);
            } else {
                txtAddress.setBackground(Color.white);
            }
            String tel = "^0\\d{9}$";
            Pattern p = Pattern.compile(tel);
            Matcher matcher = p.matcher(txtPhone.getText());
//            sb.append( "Information is valid\n");
            if (matcher.find() == false) {
                sb.append("Telephone is invalid!\nCheck your numberphone\n");
                txtPhone.setBackground(Color.yellow);
            } else {
                txtPhone.setBackground(Color.white);
            }

            String email = "\\w+@\\w+.\\w+";
            Pattern p_email = Pattern.compile(email);
            Matcher matcher_email = p_email.matcher(txtEmail.getText());
//            sb.append("Email is valid\n");
            txtEmail.setBackground(Color.white);
            if (sb.length() > 0) {
                JOptionPane.showMessageDialog(this, sb.toString(), "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Class.forName(driver);
            java.sql.Connection con = DriverManager.getConnection(Url, username, password);

            String sql = "insert into taikhoan2 values (?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(sql); // cho phep chi dinh tham so dau vao khi chay
            ps.setString(1, txtuserName.getText());
            ps.setString(2, new String(txtPassword.getPassword()));
            ps.setString(3, txtname.getText());
            ps.setString(4, txtAddress.getText());
            ps.setString(5, txtEmail.getText());
            ps.setString(6, txtPhone.getText());

            int rs = ps.executeUpdate();

            if (rs != 0) {
                JOptionPane.showMessageDialog(this, "Sign up successfully!");

                signinform sign = new signinform();
                sign.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Sign up failurely!");
            }
            con.close();
        } catch (Exception e) {
            // e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: Username is exist", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSignupActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JPasswordField txtConfirmPass;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtuserName;
    // End of variables declaration//GEN-END:variables
}
