/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import Helper.KhachHangDao;
import Helper.ShareData;
import Helper.sqlHelper;
import java.awt.Color;
//import java.io.FileNotFoundException
import java.util.ArrayList;
import code.*;
import com.sun.jdi.connect.spi.Connection;
import java.beans.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 *
 * @author dell
 */
public class signinform extends javax.swing.JFrame {

    /**
     * Creates new form bill
     */
    infor ifo;
    ArrayList<infor> i4 = new ArrayList<>();
    String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String Url = "jdbc:sqlserver://DESKTOP-TAQ595G\\SQLEXPRESS2:1433;database=BTL_OOP2;";
    String username = "sa";
    String password = "1234";
    Statement st;
    ResultSet rs;

    @SuppressWarnings("unchecked")

    public signinform() {
        initComponents();
        setLocationRelativeTo(null);
        //this.getContentPane().setBackground( Color.pink );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 50)); // NOI18N
        jLabel1.setText("Sign In");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 13, 140, 110));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 76, 508, 10));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel2.setText("Username ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 142, 173, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 210, 173, -1));

        btncancel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btncancel.setText("Sign up");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        getContentPane().add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 383, -1, -1));

        btnOk.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnOk.setText("Sign in");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 383, -1, -1));

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 360, 39));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel4.setText("If you haven't had an account yet, please create a new account now");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 316, 540, -1));
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 360, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Downloads\\abcc.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        signupform ch = new signupform();
        ch.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btncancelActionPerformed


    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO vczxhjuu21 add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed
    public static String user = "";
    public static String sdt = "";
    public static String diachi = "";
    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if (txtname.getText().equals("")) {
            sb.append("Ten dang nhap khong duoc bo trong!");
            txtname.setBackground(Color.yellow);
            txtname.requestFocus();
        } else {
            txtname.setBackground(Color.white);
        }
        if (new String(txtpass.getPassword()).equals("")) {
            sb.append("\nMat khau khong duoc bo trong!");
            txtpass.setBackground(Color.yellow);
            txtpass.requestFocus();
        } else {
            txtpass.setBackground(Color.white);
        }

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Loi", JOptionPane.ERROR_MESSAGE);
            return;
        }
//        String sql = "select * from taikhoan where username =? and pword =?";
        KhachHangDao khachHangDao = new KhachHangDao();
//        try {
//            Class.forName(driver);
//            java.sql.Connection con = DriverManager.getConnection(Url, username, password);
//
//            String sql = "select * from taikhoan2 where username =? and pass =?";
//            PreparedStatement ps = con.prepareStatement(sql); // cho phep chi dinh tham so dau vao khi chay
//            ps.setString(1, txtname.getText());
//            ps.setString(2, new String(txtpass.getPassword()));
//            ResultSet rs = ps.executeQuery();
           try {
            KhachHang kh = khachHangDao.checkLogin(txtname.getText(), new String(txtpass.getPassword()));
            if (kh == null) {
                JOptionPane.showMessageDialog(this, "Ten dang nhap hoac mat khau khong hop le!");
            } else {
                JOptionPane.showMessageDialog(this, "Dang nhap thanh cong!");
                ShareData.nguoiDangNhap = kh;
                HoaDonform mn = new HoaDonform();
                mn.setVisible(true);
                this.setVisible(false);
            }
        } catch (Exception e) {
               // e.printStackTrace();
        }

    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signinform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btncancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
